version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "pandas"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pyyaml"
        update-types: ["version-update:semver-major"]
      - dependency-name: "appium-python-client"
        update-types: ["version-update:semver-major"]
      - dependency-name: "lxml"
        update-types: ["version-update:semver-major"]
      - dependency-name: "fuzzywuzzy"
        update-types: ["version-update:semver-major"]
      - dependency-name: "opencv-python"
        update-types: ["version-update:semver-major"]
      - dependency-name: "python-levenshtein"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sphinx-autobuild"
        update-types: ["version-update:semver-major"]
      - dependency-name: "prompt-toolkit"
        update-types: ["version-update:semver-major"]
      - dependency-name: "rich"
        update-types: ["version-update:semver-major"]
      - dependency-name: "python-json-logger"
        update-types: ["version-update:semver-major"]
      - dependency-name: "easyocr"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pytesseract"
        update-types: ["version-update:semver-major"]
      - dependency-name: "google-cloud-vision"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sse-starlette"
        update-types: ["version-update:semver-major"]
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
      - dependency-name: "selenium"
        update-types: ["version-update:semver-major"]
      - dependency-name: "black"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tox"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pytest"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pytest-cov"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pylint"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sphinx"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pydata-sphinx-theme"
        update-types: ["version-update:semver-major"]
      - dependency-name: "sphinx-autoapi"
        update-types: ["version-update:semver-major"]
