"""MCP (Model Context Protocol) server exposing optics-framework keywords.

Launched via ``optics mcp``. This wraps the in-process keyword machinery in
``optics_framework.common.expose_api`` (the same async functions the HTTP server
``optics serve`` uses) and surfaces it over MCP so an LLM client (Claude
Desktop/Code, Cursor, ...) can drive a live device/browser session.

Shape (hybrid):
- Each optics *action* keyword becomes its own typed MCP **tool** (each takes an
  explicit ``session_id``). Tool parameters are reflected from the real API-class
  method signatures but typed as ``str`` because the underlying
  ``ExecuteRequest.params`` boundary is string-only.
- Read-only device state is exposed as MCP **resources** (screenshot, page
  source, interactive elements, screen elements) plus the keyword catalog.

``fastmcp`` is an optional dependency: ``pip install optics-framework[mcp]``.

Process-isolation note: ``optics mcp`` and ``optics serve`` are separate OS
processes. ``SessionManager`` is in-memory, so sessions are NOT shared between
them. A client must call ``start_session`` before any keyword tool will work.
"""

from __future__ import annotations

import asyncio
import base64
import inspect
import json
import os
from typing import Any, Callable, Optional

from fastapi import HTTPException

from optics_framework.api.action_keyword import ActionKeyword
from optics_framework.api.app_management import AppManagement
from optics_framework.api.verifier import Verifier
from optics_framework.common import expose_api
from optics_framework.common.error import OpticsError
from optics_framework.common.logging_config import internal_logger
from optics_framework.common.session_manager import _get_enabled_config_list
from optics_framework.helper import mcp_authoring, mcp_diagnostics
from optics_framework.helper.version import VERSION

# Workspace where MCP-authored suites live (a canonical optics CSV project).
ENV_WORKSPACE = "OPTICS_MCP_WORKSPACE"
_DEFAULT_WORKSPACE = os.path.join(os.path.expanduser("~"), ".optics", "mcp_workspace")

# A minimal, `optics execute`-able config used by `export_optics_project` when no
# live session is available to derive the real driver/source config from.
_DEFAULT_CONFIG_TEMPLATE = """\
# Generated by `optics mcp` export. Fill in the Appium URL/capabilities for your
# device, then run `optics execute <this folder>`.
driver_sources:
  - appium:
      enabled: true
      url: "http://localhost:4723"
      capabilities:
        platformName: Android
        automationName: UiAutomator2
        deviceName: emulator-5554

elements_sources:
  - appium_find_element:
      enabled: true
  - appium_page_source:
      enabled: true
  - appium_screenshot:
      enabled: true

text_detection: []
image_detection: []
"""

# fastmcp is optional (extra: mcp). Import lazily with a clear, actionable error.
try:
    from fastmcp import FastMCP
    from fastmcp.exceptions import ToolError
    from fastmcp.tools.tool import Tool
    from fastmcp.utilities.types import Image

    _FASTMCP_IMPORT_ERROR: Optional[ImportError] = None
except ImportError as _e:  # pragma: no cover - exercised only without the extra
    FastMCP = None  # type: ignore[assignment,misc]
    ToolError = RuntimeError  # type: ignore[assignment,misc]
    Tool = None  # type: ignore[assignment,misc]
    Image = None  # type: ignore[assignment,misc]
    _FASTMCP_IMPORT_ERROR = _e

SERVER_NAME = "Optics MCP"
SERVER_INSTRUCTIONS = (
    "Drive a live device/browser through the optics-framework, then turn the "
    "session into a reusable test suite.\n"
    "Onboard: `doctor` checks your environment (adb/SDK/Appium) with fixes; "
    "`list_devices` shows connected devices; `list_available_sources` lists engine "
    "source names.\n"
    "1. `start_session` opens a session against your driver (e.g. appium) and "
    "returns a `session_id`. Element sources default sensibly per driver, so "
    "`start_session(driver=\"appium\")` just works. Reconnect later with "
    "`list_sessions` / `session_info`.\n"
    "2. Pass that `session_id` to keyword tools (press_element, enter_text, swipe, "
    "assert_presence, ...). Inspect the screen with `find_elements` (filtered, "
    "compact) and `get_screen_size` instead of eyeballing pixels; on Android, "
    "`get_current_app` / `list_installed_apps` avoid guessing packages.\n"
    "3. Record & build a suite: `start_recording`, run the keywords, drop mis-fires "
    "with `remove_step`/`edit_step`, then `save_test_case` (optionally with "
    "`${var}` `variables`). Replay with `run_test_case` / `run_suite` (per-step "
    "pass/fail + failure screenshot). `export_optics_project` writes a standalone "
    "`optics execute` project; `import_optics_project` reads one back.\n"
    "4. `terminate_session` when done.\n"
    "Sessions and recordings live only inside this server process; they are not "
    "shared with `optics serve` or `optics live`."
)

# API classes whose public methods become keyword tools — the same set the HTTP
# `execute_keyword` registry builds (FlowControl is intentionally excluded; it
# needs runner context).
_KEYWORD_CLASSES = (ActionKeyword, AppManagement, Verifier)

# Read-only observers surfaced as resources instead of action tools.
# `get_interactive_elements` is intentionally NOT here: it takes `filter_config`
# (which resources cannot accept), so it stays a tool AND is mirrored as an
# unfiltered resource.
_RESOURCE_ONLY_KEYWORDS = frozenset(
    {"capture_screenshot", "capture_pagesource", "get_screen_elements"}
)

_RESULT_KEY = expose_api.KEY_RESULT


def _require_fastmcp() -> None:
    if _FASTMCP_IMPORT_ERROR is not None:
        raise RuntimeError(
            "The 'mcp' extra is required to run the Optics MCP server. "
            "Install it with: pip install 'optics-framework[mcp]'"
        ) from _FASTMCP_IMPORT_ERROR


def _http_detail(detail: Any) -> str:
    """Render an HTTPException detail (str or optics error payload dict) to text."""
    if isinstance(detail, dict):
        # OpticsError.to_payload(include_status=True) shape: prefer message/code.
        msg = detail.get("message") or detail.get("detail") or detail
        code = detail.get("code")
        return f"[{code}] {msg}" if code else str(msg)
    return str(detail)


def _stringify_params(kwargs: dict[str, Any]) -> dict[str, Any]:
    """Coerce tool kwargs to the string-only ExecuteRequest.params contract.

    None values are dropped so keyword defaults apply; lists are stringified
    element-wise (the param-fallback ladder consumes List[str]).
    """
    out: dict[str, Any] = {}
    for key, value in kwargs.items():
        if value is None:
            continue
        if isinstance(value, list):
            out[key] = [str(item) for item in value]
        else:
            out[key] = str(value)
    return out


def _reflect_keyword_params(method: Callable[..., Any]) -> list[inspect.Parameter]:
    """Real (name, default) params of an API method, excluding self."""
    sig = inspect.signature(method)
    return [
        p
        for name, p in sig.parameters.items()
        if name != "self"
        # *args / **kwargs can't be represented as discrete string tool params.
        and p.kind not in (inspect.Parameter.VAR_POSITIONAL, inspect.Parameter.VAR_KEYWORD)
    ]


def _make_keyword_tool(slug: str, params: list[inspect.Parameter]) -> Callable[..., Any]:
    """Synthesize a str-typed wrapper that dispatches `slug` via execute_keyword.

    The wrapper's exposed signature is `session_id: str` followed by the
    keyword's params, every annotation forced to `str` (or `str | None` when the
    default is None) so fastmcp/pydantic emit a clean, consistent schema.
    """

    async def wrapper(**kwargs: Any) -> Any:
        """Run the keyword. On an AI self-heal, return the whole {result, healed, ...}
        dict so the client sees the recovery; otherwise unwrap to the bare result.
        """
        session_id = kwargs.pop("session_id")
        request = expose_api.ExecuteRequest(
            mode=expose_api.MODE_KEYWORD,
            keyword=slug,
            params=_stringify_params(kwargs),
        )
        try:
            response = await expose_api.execute_keyword(session_id, request)
        except HTTPException as exc:
            raise ToolError(_http_detail(exc.detail)) from exc
        except OpticsError as exc:  # pragma: no cover - defensive
            raise ToolError(str(exc)) from exc
        # Only a successful call is recorded, so mis-fires stay out of the suite.
        _record_keyword(session_id, slug, params, request.params)
        data = getattr(response, "data", None) or {}
        if "healed" in data:
            return data
        return data.get(_RESULT_KEY, data)

    synth: list[inspect.Parameter] = [
        inspect.Parameter("session_id", inspect.Parameter.KEYWORD_ONLY, annotation=str)
    ]
    annotations: dict[str, Any] = {"session_id": str}
    for param in params:
        name = param.name
        if param.default is inspect.Parameter.empty:
            synth.append(
                inspect.Parameter(name, inspect.Parameter.KEYWORD_ONLY, annotation=str)
            )
            annotations[name] = str
        elif param.default is None:
            synth.append(
                inspect.Parameter(
                    name,
                    inspect.Parameter.KEYWORD_ONLY,
                    annotation=Optional[str],
                    default=None,
                )
            )
            annotations[name] = Optional[str]
        else:
            synth.append(
                inspect.Parameter(
                    name,
                    inspect.Parameter.KEYWORD_ONLY,
                    annotation=str,
                    default=str(param.default),
                )
            )
            annotations[name] = str

    wrapper.__signature__ = inspect.Signature(synth)  # type: ignore[attr-defined]
    wrapper.__annotations__ = {**annotations, "return": Any}
    wrapper.__name__ = slug
    return wrapper


def _iter_keyword_tools() -> list[tuple[str, str, Callable[..., Any]]]:
    """Yield (slug, description, wrapper) for every action keyword to register."""
    tools: list[tuple[str, str, Callable[..., Any]]] = []
    seen: set[str] = set()
    for cls in _KEYWORD_CLASSES:
        for name, method in inspect.getmembers(cls, predicate=inspect.isfunction):
            if name.startswith("_") or name.startswith("test"):
                continue
            if name in _RESOURCE_ONLY_KEYWORDS or name in seen:
                continue
            seen.add(name)
            description = inspect.getdoc(method) or expose_api._humanize_keyword(name)
            wrapper = _make_keyword_tool(name, _reflect_keyword_params(method))
            tools.append((name, description, wrapper))
    return tools


async def _observe(session_id: str, keyword: str) -> Any:
    """Run a read-only observer keyword and return its unwrapped result."""
    try:
        response = await expose_api.run_keyword_endpoint(session_id, keyword)
    except HTTPException as exc:
        raise ToolError(_http_detail(exc.detail)) from exc
    data = getattr(response, "data", None) or {}
    return data.get(_RESULT_KEY, data)


def _decode_screenshot(result: Any) -> bytes:
    """Decode a base64 screenshot result (raw base64 or data URL) to raw bytes."""
    if isinstance(result, bytes):
        return result
    if not isinstance(result, str):
        raise ToolError("Screenshot result was not a base64 string")
    payload = result.split(",", 1)[1] if result.startswith("data:") else result
    return base64.b64decode(payload)


# --------------------------------------------------------------------------- #
# Extension helpers (onboarding, discovery, recording, suites, replay)
# --------------------------------------------------------------------------- #
def _workspace_root() -> str:
    """Root of the MCP suite workspace (env override or ``~/.optics/mcp_workspace``)."""
    return os.environ.get(ENV_WORKSPACE) or _DEFAULT_WORKSPACE


def _suite_store() -> "mcp_authoring.SuiteStore":
    return mcp_authoring.SuiteStore(_workspace_root())


def _require_session(session_id: str) -> Any:
    session = expose_api.session_manager.get_session(session_id)
    if session is None:
        raise ToolError(f"Session not found: {session_id}")
    return session


def _record_keyword(
    session_id: str, slug: str, params: list[inspect.Parameter], stringified: Any
) -> None:
    """Append a successful keyword call to the session's recording, if one is active."""
    if slug in mcp_authoring.NON_RECORDED_KEYWORDS or not isinstance(stringified, dict):
        return
    specs = [
        (p.name, None if p.default is inspect.Parameter.empty else str(p.default))
        for p in params
    ]
    tokens = mcp_authoring.format_step_params(specs, stringified)
    mcp_authoring.RECORDERS.record(session_id, mcp_authoring.RecordedStep(slug, tokens))


def _to_int(value: Any, default: int) -> int:
    try:
        return int(str(value).strip())
    except (TypeError, ValueError):
        return default


def _parse_region(value: Optional[str]) -> Optional[tuple[int, int, int, int]]:
    if not value:
        return None
    parts = [p.strip() for p in value.split(",")]
    if len(parts) != 4:
        raise ToolError("region must be 'x1,y1,x2,y2'")
    try:
        x1, y1, x2, y2 = (int(p) for p in parts)
    except ValueError as exc:
        raise ToolError("region coordinates must be integers") from exc
    return x1, y1, x2, y2


def _parse_json_object(value: Optional[str], label: str) -> dict[str, str]:
    """Parse an MCP JSON-object string arg to ``{str: str}`` (empty when unset)."""
    if not value:
        return {}
    try:
        parsed = json.loads(value)
    except (ValueError, TypeError) as exc:
        raise ToolError(f"{label} must be a JSON object string, e.g. '{{\"hour\": \"22\"}}'") from exc
    if not isinstance(parsed, dict):
        raise ToolError(f"{label} must be a JSON object")
    return {str(k): str(v) for k, v in parsed.items()}


def _parse_str_list(value: Optional[str]) -> Optional[list[str]]:
    """Parse an MCP JSON-array string arg to ``list[str]`` (``None`` when unset)."""
    if value is None:
        return None
    try:
        parsed = json.loads(value)
    except (ValueError, TypeError) as exc:
        raise ToolError("params must be a JSON array of strings, e.g. '[\"Login\"]'") from exc
    if not isinstance(parsed, list):
        raise ToolError("params must be a JSON array")
    return [str(v) for v in parsed]


def _parse_steps(value: str) -> list["mcp_authoring.RecordedStep"]:
    """Parse an explicit steps arg (JSON list of ``{keyword, params}``) to steps."""
    try:
        parsed = json.loads(value)
    except (ValueError, TypeError) as exc:
        raise ToolError("steps must be a JSON array of {keyword, params} objects") from exc
    if not isinstance(parsed, list):
        raise ToolError("steps must be a JSON array")
    steps: list[mcp_authoring.RecordedStep] = []
    for item in parsed:
        if not isinstance(item, dict) or "keyword" not in item:
            raise ToolError("each step needs a 'keyword' (and optional 'params' list)")
        raw_params = item.get("params") or []
        steps.append(
            mcp_authoring.RecordedStep(
                mcp_authoring.title_to_slug(str(item["keyword"])),
                [str(p) for p in raw_params],
            )
        )
    return steps


def _png_dimensions(data: bytes) -> tuple[int, int]:
    """Width/height of a PNG from its IHDR chunk (no image library needed)."""
    if len(data) < 24 or data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ToolError("Screenshot was not a PNG image")
    return int.from_bytes(data[16:20], "big"), int.from_bytes(data[20:24], "big")


def _compact_element(element: dict[str, Any]) -> dict[str, Any]:
    """A small, stable view of an interactive element (id/class/tag/center/bounds)."""
    bounds = element.get("bounds") or {}
    extra = element.get("extra") or {}
    center: Optional[list[int]] = None
    if bounds:
        cx = (_to_int(bounds.get("x1"), 0) + _to_int(bounds.get("x2"), 0)) // 2
        cy = (_to_int(bounds.get("y1"), 0) + _to_int(bounds.get("y2"), 0)) // 2
        center = [cx, cy]
    return {
        "text": element.get("text"),
        "xpath": element.get("xpath"),
        "id": extra.get("resource-id") or extra.get("id"),
        "class": extra.get("class"),
        "tag": extra.get("tag"),
        "clickable": extra.get("clickable"),
        "center": center,
        "bounds": bounds or None,
    }


def _element_matches(
    element: dict[str, Any],
    *,
    text: Optional[str],
    resource_id: Optional[str],
    class_name: Optional[str],
    clickable: Optional[bool],
    region: Optional[tuple[int, int, int, int]],
) -> bool:
    extra = element.get("extra") or {}
    if text and text.lower() not in str(element.get("text") or "").lower():
        return False
    if resource_id:
        rid = str(extra.get("resource-id") or extra.get("id") or "")
        if resource_id.lower() not in rid.lower():
            return False
    if class_name:
        cls = str(extra.get("class") or extra.get("tag") or "")
        if class_name.lower() not in cls.lower():
            return False
    if clickable is not None:
        is_clickable = str(extra.get("clickable") or "").strip().lower() == "true"
        if is_clickable != clickable:
            return False
    if region:
        bounds = element.get("bounds") or {}
        if not bounds:
            return False
        cx = (_to_int(bounds.get("x1"), 0) + _to_int(bounds.get("x2"), 0)) // 2
        cy = (_to_int(bounds.get("y1"), 0) + _to_int(bounds.get("y2"), 0)) // 2
        x1, y1, x2, y2 = region
        if not (x1 <= cx <= x2 and y1 <= cy <= y2):
            return False
    return True


def _filter_elements(
    elements: list[dict[str, Any]],
    *,
    text: Optional[str] = None,
    resource_id: Optional[str] = None,
    class_name: Optional[str] = None,
    clickable: Optional[bool] = None,
    region: Optional[tuple[int, int, int, int]] = None,
    offset: int = 0,
    limit: int = 20,
    compact: bool = True,
) -> dict[str, Any]:
    """Filter/paginate/compact an interactive-elements list (pure)."""
    matched = [
        el
        for el in elements
        if _element_matches(
            el,
            text=text,
            resource_id=resource_id,
            class_name=class_name,
            clickable=clickable,
            region=region,
        )
    ]
    offset = max(0, offset)
    window = matched[offset: offset + limit] if limit >= 0 else matched[offset:]
    shaped = [_compact_element(el) if compact else el for el in window]
    return {
        "total": len(matched),
        "returned": len(shaped),
        "offset": offset,
        "limit": limit,
        "elements": shaped,
    }


def _session_capabilities(session: Any) -> dict[str, Any]:
    """Merged capabilities of the session's first enabled driver source ({} if none)."""
    for entry in getattr(session.config, "driver_sources", None) or []:
        for _name, dependency in entry.items():
            if getattr(dependency, "enabled", True):
                return dict(getattr(dependency, "capabilities", None) or {})
    return {}


def _session_device_serial(session: Any) -> Optional[str]:
    caps = _session_capabilities(session)
    for key in ("udid", "deviceUDID", "appium:udid", "deviceName", "appium:deviceName"):
        value = caps.get(key)
        if value:
            return str(value)
    return None


def _session_platform(session: Any) -> Optional[str]:
    caps = _session_capabilities(session)
    platform = caps.get("platformName") or caps.get("appium:platformName")
    return str(platform).strip().lower() if platform else None


def _serialize_session(session_id: str, session: Any, *, full: bool) -> dict[str, Any]:
    recorder = mcp_authoring.RECORDERS.peek(session_id)
    info: dict[str, Any] = {
        "session_id": session_id,
        "drivers": [
            name
            for entry in _get_enabled_config_list(session.config, expose_api.KEY_DRIVER_SOURCES)
            for name in entry
        ],
        "project_path": getattr(session.config, "project_path", None),
        "recording": bool(recorder and recorder.active),
        "recorded_steps": len(recorder.steps) if recorder else 0,
    }
    if full:
        info["elements_sources"] = _get_enabled_config_list(session.config, "elements_sources")
        info["text_detection"] = _get_enabled_config_list(session.config, "text_detection")
        info["image_detection"] = _get_enabled_config_list(session.config, "image_detection")
        info["platform"] = _session_platform(session)
        info["device"] = _session_device_serial(session)
        info["ai_self_heal"] = getattr(session.config, "ai_self_heal", False)
    return info


def _session_config_yaml(session_id: Optional[str]) -> str:
    """A config.yaml for export — derived from a live session, else the template."""
    if session_id:
        session = expose_api.session_manager.get_session(session_id)
        if session is not None:
            try:
                import yaml  # lazy: pyyaml is a core dep but keep the import local

                config_dict = {
                    key: _get_enabled_config_list(session.config, key)
                    for key in (
                        expose_api.KEY_DRIVER_SOURCES,
                        "elements_sources",
                        "text_detection",
                        "image_detection",
                    )
                }
                return yaml.safe_dump(config_dict, sort_keys=False)
            except Exception:  # noqa: BLE001 - fall back to the template on any error
                internal_logger.warning("Could not derive config.yaml from session %s", session_id)
    return _DEFAULT_CONFIG_TEMPLATE


async def _replay_step(session_id: str, slug: str, args: list[str]) -> dict[str, Any]:
    """Run one recorded step against a live session; report pass/fail, never raise."""
    request = expose_api.ExecuteRequest(
        mode=expose_api.MODE_KEYWORD, keyword=slug, params=list(args)
    )
    try:
        response = await expose_api.execute_keyword(session_id, request)
    except HTTPException as exc:
        return {"ok": False, "status": expose_api.STATUS_FAIL, "detail": _http_detail(exc.detail)}
    except OpticsError as exc:  # pragma: no cover - defensive
        return {"ok": False, "status": expose_api.STATUS_FAIL, "detail": str(exc)}
    data = getattr(response, "data", None) or {}
    return {
        "ok": True,
        "status": expose_api.STATUS_SUCCESS,
        "result": data.get(_RESULT_KEY, data),
    }


async def _safe_screenshot_b64(session_id: str) -> Optional[str]:
    """Best-effort base64 PNG of the current screen (``None`` on any failure)."""
    try:
        result = await _observe(session_id, "capture_screenshot")
    except Exception:  # noqa: BLE001 - a failure screenshot is best-effort
        return None
    return result if isinstance(result, str) else None


async def _run_test_case(
    session_id: str, name: str, params: dict[str, str], continue_on_error: bool
) -> dict[str, Any]:
    """Replay a stored test case step-by-step with per-step results."""
    store = _suite_store()
    try:
        steps = store.resolve_steps(name, params)
    except mcp_authoring.SuiteNotFoundError as exc:
        raise ToolError(str(exc)) from exc
    except KeyError as exc:
        raise ToolError(f"Unresolved variable {exc}; pass it in params") from exc

    results: list[dict[str, Any]] = []
    passed = failed = 0
    for index, (slug, args) in enumerate(steps):
        outcome = await _replay_step(session_id, slug, args)
        row = {
            "index": index,
            "keyword": mcp_authoring.keyword_to_title(slug),
            "params": args,
            **outcome,
        }
        if outcome["ok"]:
            passed += 1
        else:
            failed += 1
            row["screenshot"] = await _safe_screenshot_b64(session_id)
        results.append(row)
        if not outcome["ok"] and not continue_on_error:
            break

    return {
        "test_case": name,
        "status": expose_api.STATUS_SUCCESS if failed == 0 else expose_api.STATUS_FAIL,
        "total": len(steps),
        "passed": passed,
        "failed": failed,
        "steps": results,
    }


def _register_extension_tools(mcp: "FastMCP") -> None:
    """Register the onboarding, discovery, recording, and suite tools on ``mcp``.

    These are hand-written tools (not reflected keywords): they add the "session as
    reusable artifact" surface the keyword tools lack. All parameters are ``str``
    (the MCP boundary), matching the reflected keyword tools.
    """

    # -- Onboarding & environment --------------------------------------------- #
    async def doctor(
        project_path: Optional[str] = None,
        appium_host: str = "127.0.0.1",
        appium_port: str = "4723",
    ) -> dict[str, Any]:
        """Diagnose the local environment for driving a device — the same checks as
        `optics doctor`: Python, engine backends, adb + attached devices, Appium
        reachability (at `appium_host`:`appium_port`), and browser binaries. Each row
        reports {name, status, ok, detail} and an actionable `fix` on warn/fail. Pass
        `project_path` to also validate a project's config.yaml. Run this first when
        `start_session` errors."""
        return await asyncio.to_thread(
            mcp_diagnostics.run_doctor, project_path, appium_host, _to_int(appium_port, 4723)
        )

    async def list_devices() -> list[dict[str, str]]:
        """List connected mobile devices as {udid, platform} via adb (Android) and
        idevice_id (iOS). An empty list can mean nothing is connected or the tool
        is not installed — `doctor` reports which."""
        return await asyncio.to_thread(mcp_diagnostics.list_connected_devices)

    def list_available_sources(driver: Optional[str] = None) -> dict[str, Any]:
        """List installed engine sources (element/text/image) by name, so you never
        have to guess module names for `start_session`. Pass a `driver` (e.g.
        "appium") to see just that driver's element sources in priority order."""
        return mcp_diagnostics.list_available_sources(driver)

    # -- Session durability --------------------------------------------------- #
    def list_sessions() -> list[dict[str, Any]]:
        """List the sessions live in this server process, with their drivers and
        whether a recording is active — reconnect to long-running work after a
        context reset instead of recreating the session."""
        return [
            _serialize_session(sid, session, full=False)
            for sid, session in expose_api.session_manager.sessions.items()
        ]

    def session_info(session_id: str) -> dict[str, Any]:
        """Full detail for one session: enabled sources, platform, device serial,
        AI self-heal, and recording status."""
        session = _require_session(session_id)
        return _serialize_session(session_id, session, full=True)

    # -- Discovery & reliability ---------------------------------------------- #
    async def get_screen_size(session_id: str) -> dict[str, int]:
        """Current screen dimensions {width, height} in pixels. Combine with the
        `bounds`/`center` from `find_elements` to target taps exactly instead of
        eyeballing coordinates on a screenshot."""
        _require_session(session_id)
        raw = _decode_screenshot(await _observe(session_id, "capture_screenshot"))
        width, height = _png_dimensions(raw)
        return {"width": width, "height": height}

    async def find_elements(
        session_id: str,
        text: Optional[str] = None,
        resource_id: Optional[str] = None,
        class_name: Optional[str] = None,
        clickable: Optional[str] = None,
        region: Optional[str] = None,
        offset: str = "0",
        limit: str = "20",
        compact: str = "true",
    ) -> dict[str, Any]:
        """Find on-screen elements with filtering and pagination — the compact,
        token-safe way to inspect the screen. Filters (all case-insensitive
        substrings, AND-combined): `text`, `resource_id`, `class_name`; `clickable`
        ("true"/"false"); `region` ("x1,y1,x2,y2" — keeps elements whose center is
        inside). `offset`/`limit` paginate; `compact` ("true") returns
        text/id/class/tag/center/bounds, else full raw elements. Prefer targeting a
        result's `xpath`/`text` with `press_element` over raw coordinates."""
        _require_session(session_id)
        elements = await _observe(session_id, "get_interactive_elements")
        if not isinstance(elements, list):
            elements = []
        return _filter_elements(
            elements,
            text=text,
            resource_id=resource_id,
            class_name=class_name,
            clickable=None if clickable is None else mcp_diagnostics.is_truthy(clickable),
            region=_parse_region(region),
            offset=_to_int(offset, 0),
            limit=_to_int(limit, 20),
            compact=mcp_diagnostics.is_truthy(compact),
        )

    async def get_current_app(session_id: str) -> dict[str, Any]:
        """Foreground app {package, activity} for sanity-checking state mid-flow.
        Android-only (reads `adb dumpsys`), best-effort."""
        session = _require_session(session_id)
        platform = _session_platform(session)
        if platform and platform != "android":
            raise ToolError(f"get_current_app is Android-only (adb); this session is {platform}.")
        try:
            return await asyncio.to_thread(
                mcp_diagnostics.get_foreground_app, _session_device_serial(session)
            )
        except RuntimeError as exc:
            raise ToolError(str(exc)) from exc

    async def list_installed_apps(session_id: str, query: Optional[str] = None) -> list[str]:
        """List installed package ids so you don't have to guess an app's package.
        `query` is a case-insensitive substring filter. Android-only (`adb pm list
        packages`), best-effort."""
        session = _require_session(session_id)
        platform = _session_platform(session)
        if platform and platform != "android":
            raise ToolError(f"list_installed_apps is Android-only (adb); this session is {platform}.")
        try:
            return await asyncio.to_thread(
                mcp_diagnostics.list_installed_packages, _session_device_serial(session), query
            )
        except RuntimeError as exc:
            raise ToolError(str(exc)) from exc

    # -- Recording ------------------------------------------------------------ #
    def start_recording(session_id: str) -> dict[str, Any]:
        """Start recording this session's keyword calls into a step buffer (clears
        any prior buffer). Every successful action keyword is captured with its
        resolved args, ready to cherry-pick into a test case."""
        _require_session(session_id)
        mcp_authoring.RECORDERS.get(session_id).start()
        return {"session_id": session_id, "recording": True}

    def stop_recording(session_id: str) -> dict[str, Any]:
        """Stop recording; keeps the captured steps for `save_test_case`."""
        recorder = mcp_authoring.RECORDERS.get(session_id)
        recorder.stop()
        return recorder.status()

    def recording_status(session_id: str) -> dict[str, Any]:
        """Whether recording is active plus the current recorded steps."""
        return mcp_authoring.RECORDERS.get(session_id).status()

    def list_recorded_steps(session_id: str) -> dict[str, Any]:
        """The recorded steps for this session (index, keyword, params)."""
        return mcp_authoring.RECORDERS.get(session_id).status()

    def edit_step(
        session_id: str,
        index: str,
        keyword: Optional[str] = None,
        params: Optional[str] = None,
    ) -> dict[str, Any]:
        """Edit a recorded step in place. `keyword` is a display name ("Press
        Element"); `params` is a JSON array of arg tokens (e.g. '["Login"]')."""
        recorder = mcp_authoring.RECORDERS.get(session_id)
        try:
            recorder.edit(_to_int(index, -1), keyword, _parse_str_list(params))
        except IndexError as exc:
            raise ToolError(str(exc)) from exc
        return recorder.status()

    def remove_step(session_id: str, index: str) -> dict[str, Any]:
        """Drop a recorded step by 0-based index (use to remove a mis-fired action)."""
        recorder = mcp_authoring.RECORDERS.get(session_id)
        try:
            recorder.remove(_to_int(index, -1))
        except IndexError as exc:
            raise ToolError(str(exc)) from exc
        return recorder.status()

    def clear_recording(session_id: str) -> dict[str, Any]:
        """Discard all recorded steps for this session."""
        recorder = mcp_authoring.RECORDERS.get(session_id)
        recorder.clear()
        return recorder.status()

    # -- Suite authoring / storage -------------------------------------------- #
    def save_test_case(
        session_id: str,
        name: str,
        steps: Optional[str] = None,
        variables: Optional[str] = None,
        overwrite: str = "false",
    ) -> dict[str, Any]:
        """Save steps as a replayable test case in the MCP workspace (a real optics
        CSV project). By default it saves this session's current recording; pass
        `steps` (JSON list of {keyword, params}) to save an explicit sequence.
        `variables` (JSON object {name: default}) parameterizes the module: any arg
        equal to a default becomes ${name}, so `run_test_case` can override it.
        `overwrite`="true" replaces an existing test case. Saving from the recording
        clears the buffer (one test case per save)."""
        _require_session(session_id)
        if steps:
            step_objs = _parse_steps(steps)
        else:
            step_objs = list(mcp_authoring.RECORDERS.get(session_id).steps)
        try:
            result = _suite_store().save_test_case(
                name,
                step_objs,
                _parse_json_object(variables, "variables"),
                overwrite=mcp_diagnostics.is_truthy(overwrite),
            )
        except (ValueError, mcp_authoring.SuiteConflictError) as exc:
            raise ToolError(str(exc)) from exc
        if not steps:
            mcp_authoring.RECORDERS.get(session_id).clear()
        return result

    def list_test_cases() -> list[dict[str, Any]]:
        """List saved test cases (name, modules, step count)."""
        return _suite_store().list_test_cases()

    def get_test_case(name: str) -> dict[str, Any]:
        """Get a saved test case's steps and parameter variables."""
        try:
            return _suite_store().get_test_case(name)
        except mcp_authoring.SuiteNotFoundError as exc:
            raise ToolError(str(exc)) from exc

    def delete_test_case(name: str) -> dict[str, Any]:
        """Delete a saved test case and its module rows."""
        try:
            return _suite_store().delete_test_case(name)
        except mcp_authoring.SuiteNotFoundError as exc:
            raise ToolError(str(exc)) from exc

    def save_suite(name: str, test_cases: str) -> dict[str, Any]:
        """Group saved test cases into a named suite. `test_cases` is a JSON array of
        test-case names (e.g. '["Login", "Add Contact"]')."""
        members = _parse_str_list(test_cases) or []
        try:
            return _suite_store().save_suite(name, members)
        except (ValueError, mcp_authoring.SuiteNotFoundError) as exc:
            raise ToolError(str(exc)) from exc

    def list_suites() -> list[dict[str, Any]]:
        """List saved suites and their member test cases."""
        return _suite_store().list_suites()

    def get_suite(name: str) -> dict[str, Any]:
        """Get a suite's member test cases."""
        try:
            return _suite_store().get_suite(name)
        except mcp_authoring.SuiteNotFoundError as exc:
            raise ToolError(str(exc)) from exc

    # -- Suite execution ------------------------------------------------------ #
    async def run_test_case(
        session_id: str,
        name: str,
        params: Optional[str] = None,
        continue_on_error: str = "false",
    ) -> dict[str, Any]:
        """Replay a saved test case against the live session, returning per-step
        pass/fail plus a base64 screenshot on the failing step. `params` (JSON object
        {name: value}) overrides ${name} variables. `continue_on_error`="true" runs
        every step; the default stops at the first failure."""
        _require_session(session_id)
        return await _run_test_case(
            session_id,
            name,
            _parse_json_object(params, "params"),
            mcp_diagnostics.is_truthy(continue_on_error),
        )

    async def run_suite(
        session_id: str,
        name: str,
        params: Optional[str] = None,
        continue_on_error: str = "false",
    ) -> dict[str, Any]:
        """Replay every test case in a suite in order, returning per-test-case
        results. `continue_on_error`="true" keeps going past a failing test case."""
        _require_session(session_id)
        try:
            suite = _suite_store().get_suite(name)
        except mcp_authoring.SuiteNotFoundError as exc:
            raise ToolError(str(exc)) from exc
        parsed = _parse_json_object(params, "params")
        cont = mcp_diagnostics.is_truthy(continue_on_error)
        case_results: list[dict[str, Any]] = []
        failed = 0
        for test_case in suite["test_cases"]:
            result = await _run_test_case(session_id, test_case, parsed, cont)
            case_results.append(result)
            if result["status"] == expose_api.STATUS_FAIL:
                failed += 1
                if not cont:
                    break
        return {
            "suite": name,
            "status": expose_api.STATUS_SUCCESS if failed == 0 else expose_api.STATUS_FAIL,
            "total": len(suite["test_cases"]),
            "failed": failed,
            "test_cases": case_results,
        }

    # -- Portability ---------------------------------------------------------- #
    def export_optics_project(dest_path: str, session_id: Optional[str] = None) -> dict[str, Any]:
        """Write the MCP workspace to `dest_path` as a standalone `optics execute`-able
        project (modules/test_cases/elements CSVs + config.yaml). Pass `session_id` to
        derive config.yaml from that live session; otherwise a template is written."""
        try:
            return _suite_store().export_project(dest_path, _session_config_yaml(session_id))
        except OSError as exc:
            raise ToolError(f"Export failed: {exc}") from exc

    def import_optics_project(path: str) -> dict[str, Any]:
        """Import an existing optics CSV project into the MCP workspace so its test
        cases become listable, editable, and replayable here (append/dedup merge)."""
        try:
            return _suite_store().import_project(path)
        except (FileNotFoundError, OSError) as exc:
            raise ToolError(str(exc)) from exc

    for fn in (
        doctor,
        list_devices,
        list_available_sources,
        list_sessions,
        session_info,
        get_screen_size,
        find_elements,
        get_current_app,
        list_installed_apps,
        start_recording,
        stop_recording,
        recording_status,
        list_recorded_steps,
        edit_step,
        remove_step,
        clear_recording,
        save_test_case,
        list_test_cases,
        get_test_case,
        delete_test_case,
        save_suite,
        list_suites,
        get_suite,
        run_test_case,
        run_suite,
        export_optics_project,
        import_optics_project,
    ):
        mcp.add_tool(Tool.from_function(fn, name=fn.__name__))


def build_server() -> "FastMCP":
    """Construct the FastMCP server with all keyword tools and state resources."""
    _require_fastmcp()
    mcp = FastMCP(SERVER_NAME, instructions=SERVER_INSTRUCTIONS, version=VERSION)

    # --- Lifecycle tools -------------------------------------------------------
    async def start_session(
        driver: str = "appium",
        url: Optional[str] = None,
        capabilities: Optional[dict[str, Any]] = None,
        elements_sources: Optional[list[str]] = None,
        text_detection: Optional[list[str]] = None,
        image_detection: Optional[list[str]] = None,
        project_path: Optional[str] = None,
        ai_self_heal: Optional[bool] = None,
        llm_provider: Optional[str] = None,
        llm_model: Optional[str] = None,
    ) -> dict[str, Any]:
        """Start a new optics session and launch the target app.

        Returns {"session_id", "driver_id"}. Pass the session_id to every
        keyword tool and state resource. The app is auto-launched on start.
        Sessions are NOT shared with `optics serve`/`optics live` (separate
        process); start one here before using any keyword tool.

        ai_self_heal / llm_provider / llm_model: per-session overrides for AI self-heal.
        Each falls back to the matching service-level env var the operator set at
        start-up (OPTICS_AI_SELF_HEAL / OPTICS_LLM_PROVIDER / OPTICS_LLM_MODEL) when left
        unset, so an already-configured server needs none of them. Because the process
        is multi-tenant, pass them to opt in/out or pick your own model for just this
        session instead of being locked to the operator's choice. Note that
        ai_self_heal=True with no provider configured anywhere still degrades to inert
        (no LLM to drive it); LLM credentials always come from the provider's own env
        vars (e.g. GOOGLE_API_KEY), never this tool.
        """
        if url or capabilities:
            driver_sources: list[Any] = [
                {driver: {"enabled": True, "url": url, "capabilities": capabilities or {}}}
            ]
        else:
            driver_sources = [driver]
        # Sane defaults: without an explicit elements_sources list, session creation
        # fails with "Element source configuration must be set". Derive the driver's
        # canonical sources (e.g. appium -> appium_find_element/page_source/screenshot)
        # so `start_session(driver="appium")` just works.
        resolved_elements = elements_sources or mcp_diagnostics.default_sources_for_driver(driver)
        config = expose_api.SessionConfig(
            driver_sources=driver_sources,
            elements_sources=resolved_elements,
            text_detection=text_detection or [],
            image_detection=image_detection or [],
            project_path=project_path,
            ai_self_heal=ai_self_heal,
            llm_provider=llm_provider,
            llm_model=llm_model,
        )
        try:
            response = await expose_api.create_session(config)
        except HTTPException as exc:
            raise ToolError(_http_detail(exc.detail)) from exc
        return {"session_id": response.session_id, "driver_id": response.driver_id}

    async def terminate_session(session_id: str) -> dict[str, str]:
        """Terminate a session and release its driver/resources."""
        try:
            await expose_api.delete_session(session_id)
        except HTTPException as exc:
            raise ToolError(_http_detail(exc.detail)) from exc
        mcp_authoring.RECORDERS.discard(session_id)
        return {"session_id": session_id, "status": "terminated"}

    async def screenshot(session_id: str) -> "Image":
        """Capture the current screen and return it as a rendered PNG image.

        Prefer this over the `optics://session/{session_id}/screenshot` resource
        when you want the screen rendered inline (the resource returns raw bytes).
        """
        raw = _decode_screenshot(await _observe(session_id, "capture_screenshot"))
        return Image(data=raw, format="png")

    mcp.add_tool(Tool.from_function(start_session, name="start_session"))
    mcp.add_tool(Tool.from_function(terminate_session, name="terminate_session"))
    mcp.add_tool(Tool.from_function(screenshot, name="screenshot"))

    # --- Per-keyword action tools ---------------------------------------------
    for slug, description, wrapper in _iter_keyword_tools():
        mcp.add_tool(Tool.from_function(wrapper, name=slug, description=description))

    # --- Onboarding / discovery / recording / suite tools ---------------------
    _register_extension_tools(mcp)

    # --- Read-only state resources --------------------------------------------
    @mcp.resource("optics://keywords", mime_type="application/json")
    def keywords_catalog() -> list[dict[str, Any]]:
        """The full optics keyword catalog (name, slug, description, params)."""
        return [info.model_dump() for info in expose_api.discover_keywords()]

    @mcp.resource("optics://session/{session_id}/screenshot", mime_type="image/png")
    async def screenshot_resource(session_id: str) -> bytes:
        """Current screen as raw PNG bytes (use the `screenshot` tool for a rendered image)."""
        return _decode_screenshot(await _observe(session_id, "capture_screenshot"))

    @mcp.resource("optics://session/{session_id}/source", mime_type="application/json")
    async def page_source(session_id: str) -> Any:
        """Current page source / UI hierarchy."""
        return await _observe(session_id, "capture_pagesource")

    @mcp.resource("optics://session/{session_id}/elements", mime_type="application/json")
    async def interactive_elements(session_id: str) -> Any:
        """All interactive elements on screen (unfiltered; use the tool to filter)."""
        return await _observe(session_id, "get_interactive_elements")

    @mcp.resource(
        "optics://session/{session_id}/screen_elements", mime_type="application/json"
    )
    async def screen_elements(session_id: str) -> Any:
        """Captured screen elements for the current screen."""
        return await _observe(session_id, "get_screen_elements")

    return mcp


def run_mcp_server(
    transport: str = "stdio", host: str = "127.0.0.1", port: int = 8090
) -> None:
    """Build and run the Optics MCP server.

    Args:
        transport: "stdio" (default, for local MCP clients) or "http".
        host: Bind host for the http transport (ignored for stdio).
        port: Bind port for the http transport (ignored for stdio).
    """
    _require_fastmcp()
    mcp = build_server()
    internal_logger.info(
        "Starting Optics MCP server (transport=%s%s)",
        transport,
        f", {host}:{port}" if transport != "stdio" else "",
    )
    if transport == "stdio":
        mcp.run(transport="stdio")
    else:
        mcp.run(transport=transport, host=host, port=port)
