name: Build-mkdocs-docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH  # Ensure Poetry is in PATH

      - name: Configure Poetry to use Python 3.12
        run: poetry env use python3.12

      - name: Ensure poetry.lock exists
        run: |
          if [ ! -f poetry.lock ]; then
            poetry lock
          fi

      - name: Install dependencies
        run: poetry install --no-interaction --with docs

      - name: Build HTML with MkDocs
        run: poetry run mkdocs build --site-dir build/html

      - name: Deploy to GitHub Pages
        run: poetry run mkdocs gh-deploy --force --no-history --site-dir build/html
